name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu çek
      uses: actions/checkout@v3

    - name: Test
      run: grep "Hello DevSecOps" hello.txt

    - name: Docker build
      run: docker build -t hello-devsecops .

    - name: Container çalıştır
      run: docker run hello-devsecops
